/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_jarlen_photoedit_filters_NativeFilter */

#ifndef _Included_cn_jarlen_photoedit_filters_NativeFilter
#define _Included_cn_jarlen_photoedit_filters_NativeFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_jarlen_photoedit_filters_NativeFilter
 * Method:    gray
 * Signature: ([IIIF)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_jarlen_photoedit_filters_NativeFilter_gray
  (JNIEnv *, jobject, jintArray, jint, jint, jfloat);

/*
 * Class:     cn_jarlen_photoedit_filters_NativeFilter
 * Method:    mosatic
 * Signature: ([IIII)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_jarlen_photoedit_filters_NativeFilter_mosatic
  (JNIEnv *, jobject, jintArray, jint, jint, jint);

/*
 * Class:     cn_jarlen_photoedit_filters_NativeFilter
 * Method:    lomo
 * Signature: ([IIIF)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_jarlen_photoedit_filters_NativeFilter_lomo
  (JNIEnv *, jobject, jintArray, jint, jint, jfloat);

/*
 * Class:     cn_jarlen_photoedit_filters_NativeFilter
 * Method:    nostalgic
 * Signature: ([IIIF)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_jarlen_photoedit_filters_NativeFilter_nostalgic
  (JNIEnv *, jobject, jintArray, jint, jint, jfloat);

/*
 * Class:     cn_jarlen_photoedit_filters_NativeFilter
 * Method:    comics
 * Signature: ([IIIF)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_jarlen_photoedit_filters_NativeFilter_comics
  (JNIEnv *, jobject, jintArray, jint, jint, jfloat);

/*
 * Class:     cn_jarlen_photoedit_filters_NativeFilter
 * Method:    brown
 * Signature: ([IIIF)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_jarlen_photoedit_filters_NativeFilter_brown
  (JNIEnv *, jobject, jintArray, jint, jint, jfloat);

/*
 * Class:     cn_jarlen_photoedit_filters_NativeFilter
 * Method:    sketchPencil
 * Signature: ([IIIF)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_jarlen_photoedit_filters_NativeFilter_sketchPencil
  (JNIEnv *, jobject, jintArray, jint, jint, jfloat);

#ifdef __cplusplus
}
#endif
#endif
