/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_jarlen_photoedit_warp_Picwarp */

#ifndef _Included_cn_jarlen_photoedit_warp_Picwarp
#define _Included_cn_jarlen_photoedit_warp_Picwarp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_jarlen_photoedit_warp_Picwarp
 * Method:    initArray
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_jarlen_photoedit_warp_Picwarp_initArray
  (JNIEnv *, jobject);

/*
 * Class:     cn_jarlen_photoedit_warp_Picwarp
 * Method:    warpPhotoFromC
 * Signature: ([IIIDDDDD)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_jarlen_photoedit_warp_Picwarp_warpPhotoFromC
  (JNIEnv *, jobject, jintArray, jint, jint, jdouble, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
